services:
  talent-hub-app:
    build:
      context: ../../
      dockerfile: docker/php/Dockerfile
    container_name: talent-hub-app
    environment:
      - PHP_ENV=${APP_ENV:-development}
    ports:
      - protocol: tcp
        published: 8000
        target: 80
    networks:
      - talent-hub-network
    depends_on:
      - talent-hub-mysql

  talent-hub-redis:
    image: redis:latest
    container_name: talent-hub-redis
    ports:
      - protocol: tcp
        published: 6379
        target: 6379
    networks:
      - talent-hub-network

  talent-hub-mysql:
    image: mysql:latest
    container_name: talent-hub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    ports:
      - "3306:3306"
    networks:
      - talent-hub-network
    depends_on:
      - talent-hub-redis

networks:
  talent-hub-network:
    driver: bridge

volumes:
  talent-hub-volume:
    name: talent-hub-volume
