services:
  talent-hub-app:
    build:
      context: ../../
      dockerfile: docker/php/Dockerfile
    container_name: talent-hub-app
    environment:
      - APP_ENV=docker

      - DB_HOST=localhost
      - DB_PASSWORD=root
      - DB_USERNAME=root
      - DB_NAME=talent_hub

      - REDIS_TYPE=docker
      - REDIS_HOST=talent-hub-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_USER=default
      - REDIS_PASSWORD=
    ports:
      - protocol: tcp
        published: 80
        target: 80
    networks:
      - talent-hub-network
    depends_on:
      - talent-hub-mysql

  talent-hub-redis:
    image: redis:latest
    container_name: talent-hub-redis
    ports:
      - protocol: tcp
        published: 6379
        target: 6379
    networks:
      - talent-hub-network

  talent-hub-mysql:
    image: mysql:latest
    container_name: talent-hub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    networks:
      - talent-hub-network
    depends_on:
      - talent-hub-redis

networks:
  talent-hub-network:
    driver: bridge

volumes:
  talent-hub-volume:
    name: talent-hub-volume
