name: Deploy Ke Infinity Free
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.19'

      - name: Create Env
        run: |
          cat > .env << 'EOF'
          APP_ENV=prod
          
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_NAME=${{ secrets.DB_NAME }}
          
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          EOF

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy via Ftp
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          server-dir: /htdocs/
          dangerous-clean-slate: true
          local-dir: ./
          exclude: |
            .git*
            .git*/**
            .idea/
            .idea/**
            .github/
            .github/**
            docker/
            docker/**
            test/
            test/**
            .dockerignore
            .env.example
            .gitignore
            .phpunit.result.cache
            design.puml
            phpunit.xml
            Readme.md